// Code generated by go-swagger; DO NOT EDIT.

package utils

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV2ProxyListServerTypesParams creates a new ControllersPublicV2ProxyListServerTypesParams object
// with the default values initialized.
func NewControllersPublicV2ProxyListServerTypesParams() *ControllersPublicV2ProxyListServerTypesParams {
	var ()
	return &ControllersPublicV2ProxyListServerTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV2ProxyListServerTypesParamsWithTimeout creates a new ControllersPublicV2ProxyListServerTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV2ProxyListServerTypesParamsWithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListServerTypesParams {
	var ()
	return &ControllersPublicV2ProxyListServerTypesParams{

		timeout: timeout,
	}
}

// NewControllersPublicV2ProxyListServerTypesParamsWithContext creates a new ControllersPublicV2ProxyListServerTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV2ProxyListServerTypesParamsWithContext(ctx context.Context) *ControllersPublicV2ProxyListServerTypesParams {
	var ()
	return &ControllersPublicV2ProxyListServerTypesParams{

		Context: ctx,
	}
}

// NewControllersPublicV2ProxyListServerTypesParamsWithHTTPClient creates a new ControllersPublicV2ProxyListServerTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV2ProxyListServerTypesParamsWithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListServerTypesParams {
	var ()
	return &ControllersPublicV2ProxyListServerTypesParams{
		HTTPClient: client,
	}
}

/*ControllersPublicV2ProxyListServerTypesParams contains all the parameters to send to the API endpoint
for the controllers public v2 proxy list server types operation typically these are written to a http.Request
*/
type ControllersPublicV2ProxyListServerTypesParams struct {

	/*Location
	  optional, default is all locations

	*/
	Location *string
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) WithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListServerTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) WithContext(ctx context.Context) *ControllersPublicV2ProxyListServerTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) WithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListServerTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLocation adds the location to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) WithLocation(location *string) *ControllersPublicV2ProxyListServerTypesParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) SetLocation(location *string) {
	o.Location = location
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV2ProxyListServerTypesParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v2 proxy list server types params
func (o *ControllersPublicV2ProxyListServerTypesParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV2ProxyListServerTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Location != nil {

		// query param location
		var qrLocation string
		if o.Location != nil {
			qrLocation = *o.Location
		}
		qLocation := qrLocation
		if qLocation != "" {
			if err := r.SetQueryParam("location", qLocation); err != nil {
				return err
			}
		}

	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
