// Code generated by go-swagger; DO NOT EDIT.

package utils

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV2ProxyListTemplatesParams creates a new ControllersPublicV2ProxyListTemplatesParams object
// with the default values initialized.
func NewControllersPublicV2ProxyListTemplatesParams() *ControllersPublicV2ProxyListTemplatesParams {
	var ()
	return &ControllersPublicV2ProxyListTemplatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV2ProxyListTemplatesParamsWithTimeout creates a new ControllersPublicV2ProxyListTemplatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV2ProxyListTemplatesParamsWithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListTemplatesParams {
	var ()
	return &ControllersPublicV2ProxyListTemplatesParams{

		timeout: timeout,
	}
}

// NewControllersPublicV2ProxyListTemplatesParamsWithContext creates a new ControllersPublicV2ProxyListTemplatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV2ProxyListTemplatesParamsWithContext(ctx context.Context) *ControllersPublicV2ProxyListTemplatesParams {
	var ()
	return &ControllersPublicV2ProxyListTemplatesParams{

		Context: ctx,
	}
}

// NewControllersPublicV2ProxyListTemplatesParamsWithHTTPClient creates a new ControllersPublicV2ProxyListTemplatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV2ProxyListTemplatesParamsWithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListTemplatesParams {
	var ()
	return &ControllersPublicV2ProxyListTemplatesParams{
		HTTPClient: client,
	}
}

/*ControllersPublicV2ProxyListTemplatesParams contains all the parameters to send to the API endpoint
for the controllers public v2 proxy list templates operation typically these are written to a http.Request
*/
type ControllersPublicV2ProxyListTemplatesParams struct {

	/*Tag
	  The specific tag to view customer specific templates.

	*/
	Tag *string
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) WithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) WithContext(ctx context.Context) *ControllersPublicV2ProxyListTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) WithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTag adds the tag to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) WithTag(tag *string) *ControllersPublicV2ProxyListTemplatesParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV2ProxyListTemplatesParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v2 proxy list templates params
func (o *ControllersPublicV2ProxyListTemplatesParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV2ProxyListTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
