// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IBM-Cloud/vcds-go-client/vcds/models"
)

// ControllersPublicV1ProxyGetServiceCatalogListReader is a Reader for the ControllersPublicV1ProxyGetServiceCatalogList structure.
type ControllersPublicV1ProxyGetServiceCatalogListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ControllersPublicV1ProxyGetServiceCatalogListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewControllersPublicV1ProxyGetServiceCatalogListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewControllersPublicV1ProxyGetServiceCatalogListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewControllersPublicV1ProxyGetServiceCatalogListOK creates a ControllersPublicV1ProxyGetServiceCatalogListOK with default headers values
func NewControllersPublicV1ProxyGetServiceCatalogListOK() *ControllersPublicV1ProxyGetServiceCatalogListOK {
	return &ControllersPublicV1ProxyGetServiceCatalogListOK{}
}

/*ControllersPublicV1ProxyGetServiceCatalogListOK handles this case with default header values.

Success.
*/
type ControllersPublicV1ProxyGetServiceCatalogListOK struct {
	/*Global transaction ID for request correlation.
	 */
	XGlobalTransactionID string

	Payload *models.ServiceCatalog
}

func (o *ControllersPublicV1ProxyGetServiceCatalogListOK) Error() string {
	return fmt.Sprintf("[GET /v1/service_catalog][%d] controllersPublicV1ProxyGetServiceCatalogListOK  %+v", 200, o.Payload)
}

func (o *ControllersPublicV1ProxyGetServiceCatalogListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-global-transaction-id
	o.XGlobalTransactionID = response.GetHeader("x-global-transaction-id")

	o.Payload = new(models.ServiceCatalog)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewControllersPublicV1ProxyGetServiceCatalogListInternalServerError creates a ControllersPublicV1ProxyGetServiceCatalogListInternalServerError with default headers values
func NewControllersPublicV1ProxyGetServiceCatalogListInternalServerError() *ControllersPublicV1ProxyGetServiceCatalogListInternalServerError {
	return &ControllersPublicV1ProxyGetServiceCatalogListInternalServerError{}
}

/*ControllersPublicV1ProxyGetServiceCatalogListInternalServerError handles this case with default header values.

Internal server error. Your request cannot be processed. Please wait a few minutes and try again.
*/
type ControllersPublicV1ProxyGetServiceCatalogListInternalServerError struct {
	/*Global transaction ID for request correlation.
	 */
	XGlobalTransactionID string

	Payload *models.Error
}

func (o *ControllersPublicV1ProxyGetServiceCatalogListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/service_catalog][%d] controllersPublicV1ProxyGetServiceCatalogListInternalServerError  %+v", 500, o.Payload)
}

func (o *ControllersPublicV1ProxyGetServiceCatalogListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header x-global-transaction-id
	o.XGlobalTransactionID = response.GetHeader("x-global-transaction-id")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
