// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV1ProxyListVcenterServicesParams creates a new ControllersPublicV1ProxyListVcenterServicesParams object
// with the default values initialized.
func NewControllersPublicV1ProxyListVcenterServicesParams() *ControllersPublicV1ProxyListVcenterServicesParams {
	var (
		installedOnlyDefault = bool(true)
	)
	return &ControllersPublicV1ProxyListVcenterServicesParams{
		InstalledOnly: &installedOnlyDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV1ProxyListVcenterServicesParamsWithTimeout creates a new ControllersPublicV1ProxyListVcenterServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV1ProxyListVcenterServicesParamsWithTimeout(timeout time.Duration) *ControllersPublicV1ProxyListVcenterServicesParams {
	var (
		installedOnlyDefault = bool(true)
	)
	return &ControllersPublicV1ProxyListVcenterServicesParams{
		InstalledOnly: &installedOnlyDefault,

		timeout: timeout,
	}
}

// NewControllersPublicV1ProxyListVcenterServicesParamsWithContext creates a new ControllersPublicV1ProxyListVcenterServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV1ProxyListVcenterServicesParamsWithContext(ctx context.Context) *ControllersPublicV1ProxyListVcenterServicesParams {
	var (
		installedOnlyDefault = bool(true)
	)
	return &ControllersPublicV1ProxyListVcenterServicesParams{
		InstalledOnly: &installedOnlyDefault,

		Context: ctx,
	}
}

// NewControllersPublicV1ProxyListVcenterServicesParamsWithHTTPClient creates a new ControllersPublicV1ProxyListVcenterServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV1ProxyListVcenterServicesParamsWithHTTPClient(client *http.Client) *ControllersPublicV1ProxyListVcenterServicesParams {
	var (
		installedOnlyDefault = bool(true)
	)
	return &ControllersPublicV1ProxyListVcenterServicesParams{
		InstalledOnly: &installedOnlyDefault,
		HTTPClient:    client,
	}
}

/*ControllersPublicV1ProxyListVcenterServicesParams contains all the parameters to send to the API endpoint
for the controllers public v1 proxy list vcenter services operation typically these are written to a http.Request
*/
type ControllersPublicV1ProxyListVcenterServicesParams struct {

	/*Authorization
	  Your IBM Cloud Identity and Access Management (IAM) token. To retrieve your IAM token, run `ibmcloud iam oauth-tokens`.

	*/
	Authorization string
	/*InstalledOnly
	  If set to true, services with REMOVED state will be excluded. Otherwise, services with INSTALLED, INSTALLING, REMOVING, REMOVED, and FAILEDVALIDATION states will be returned.

	*/
	InstalledOnly *bool
	/*InstanceID
	  Instance ID.

	*/
	InstanceID string
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithTimeout(timeout time.Duration) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithContext(ctx context.Context) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithHTTPClient(client *http.Client) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithAuthorization(authorization string) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstalledOnly adds the installedOnly to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithInstalledOnly(installedOnly *bool) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetInstalledOnly(installedOnly)
	return o
}

// SetInstalledOnly adds the installedOnly to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetInstalledOnly(installedOnly *bool) {
	o.InstalledOnly = installedOnly
}

// WithInstanceID adds the instanceID to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithInstanceID(instanceID string) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV1ProxyListVcenterServicesParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v1 proxy list vcenter services params
func (o *ControllersPublicV1ProxyListVcenterServicesParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV1ProxyListVcenterServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.InstalledOnly != nil {

		// query param installed_only
		var qrInstalledOnly bool
		if o.InstalledOnly != nil {
			qrInstalledOnly = *o.InstalledOnly
		}
		qInstalledOnly := swag.FormatBool(qrInstalledOnly)
		if qInstalledOnly != "" {
			if err := r.SetQueryParam("installed_only", qInstalledOnly); err != nil {
				return err
			}
		}

	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
