// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DefRAMTypes The list of supported RAM types in JSON format.
// swagger:model def_ram_types
type DefRAMTypes struct {

	// The list of supported RAM types.
	// Required: true
	RAMTypes []*DefRAMTypesRAMTypesItems0 `json:"ram_types"`
}

// Validate validates this def ram types
func (m *DefRAMTypes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRAMTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefRAMTypes) validateRAMTypes(formats strfmt.Registry) error {

	if err := validate.Required("ram_types", "body", m.RAMTypes); err != nil {
		return err
	}

	for i := 0; i < len(m.RAMTypes); i++ {
		if swag.IsZero(m.RAMTypes[i]) { // not required
			continue
		}

		if m.RAMTypes[i] != nil {
			if err := m.RAMTypes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ram_types" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DefRAMTypes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefRAMTypes) UnmarshalBinary(b []byte) error {
	var res DefRAMTypes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefRAMTypesRAMTypesItems0 A RAM type.
// swagger:model DefRAMTypesRAMTypesItems0
type DefRAMTypesRAMTypesItems0 struct {

	// The description of the RAM type.
	Description string `json:"description,omitempty"`

	// The RAM type ID.
	ID string `json:"id,omitempty"`

	// The list of server CPU types on which the specified RAM type is supported.
	SupportedServerTypes []string `json:"supported_server_types"`
}

// Validate validates this def RAM types RAM types items0
func (m *DefRAMTypesRAMTypesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefRAMTypesRAMTypesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefRAMTypesRAMTypesItems0) UnmarshalBinary(b []byte) error {
	var res DefRAMTypesRAMTypesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
