// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DefHistoryMessages def history messages
// swagger:model def_history_messages
type DefHistoryMessages struct {

	// history messages
	// Required: true
	HistoryMessages []*HistoryMessage `json:"history_messages"`
}

// Validate validates this def history messages
func (m *DefHistoryMessages) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHistoryMessages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefHistoryMessages) validateHistoryMessages(formats strfmt.Registry) error {

	if err := validate.Required("history_messages", "body", m.HistoryMessages); err != nil {
		return err
	}

	for i := 0; i < len(m.HistoryMessages); i++ {
		if swag.IsZero(m.HistoryMessages[i]) { // not required
			continue
		}

		if m.HistoryMessages[i] != nil {
			if err := m.HistoryMessages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("history_messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DefHistoryMessages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefHistoryMessages) UnmarshalBinary(b []byte) error {
	var res DefHistoryMessages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
