// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EdgeCustomizedHardware Customized hardware configuration to be ordered.
// swagger:model edge_customized_hardware
type EdgeCustomizedHardware struct {

	// RAM type of the hardware. To see supported RAM types, use the `GET /v2/ram_types` API.
	// Required: true
	RAM *string `json:"ram"`

	// Server CPU type of the hardware. Only one server type is supported for the edge cluster.
	// Required: true
	Server *string `json:"server"`
}

// Validate validates this edge customized hardware
func (m *EdgeCustomizedHardware) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRAM(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EdgeCustomizedHardware) validateRAM(formats strfmt.Registry) error {

	if err := validate.Required("ram", "body", m.RAM); err != nil {
		return err
	}

	return nil
}

func (m *EdgeCustomizedHardware) validateServer(formats strfmt.Registry) error {

	if err := validate.Required("server", "body", m.Server); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EdgeCustomizedHardware) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EdgeCustomizedHardware) UnmarshalBinary(b []byte) error {
	var res EdgeCustomizedHardware
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
