// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HistoryMessage history messages
// swagger:model history_message
type HistoryMessage struct {

	// Unique ID of the history record.
	// Required: true
	HistoryID *string `json:"history_id"`

	// History message.
	// Required: true
	Message *string `json:"message"`

	// Epoch timestamp of the history record.
	// Required: true
	Timestamp *string `json:"timestamp"`
}

// Validate validates this history message
func (m *HistoryMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHistoryID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HistoryMessage) validateHistoryID(formats strfmt.Registry) error {

	if err := validate.Required("history_id", "body", m.HistoryID); err != nil {
		return err
	}

	return nil
}

func (m *HistoryMessage) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *HistoryMessage) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HistoryMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HistoryMessage) UnmarshalBinary(b []byte) error {
	var res HistoryMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
