// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NetworkIP network ip
// swagger:model network_ip
type NetworkIP struct {

	// Description of the IP address.
	Desc string `json:"desc,omitempty"`

	// A fully qualified domain name of the IP address.
	Host string `json:"host,omitempty"`

	// IP address.
	// Required: true
	IPAddress *string `json:"ip_address"`

	// Status of the IP address.
	Status string `json:"status,omitempty"`
}

// Validate validates this network ip
func (m *NetworkIP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIPAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkIP) validateIPAddress(formats strfmt.Registry) error {

	if err := validate.Required("ip_address", "body", m.IPAddress); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NetworkIP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkIP) UnmarshalBinary(b []byte) error {
	var res NetworkIP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
