// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Tags tags attached to an instance
// swagger:model tags
type Tags struct {

	// list of tags attached to an instance
	Items []string `json:"items"`

	// maximum length when returning the list of tags
	Limit int64 `json:"limit,omitempty"`

	// offset value when query the tags
	Offset int64 `json:"offset,omitempty"`

	// total count of tags attached to an instance
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this tags
func (m *Tags) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tags) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tags) UnmarshalBinary(b []byte) error {
	var res Tags
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
