// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VcsEdgeOrderData vcs edge order data
// swagger:model vcs_edge_order_data
type VcsEdgeOrderData struct {

	// Active Directory DNS type. Valid values are "vsi" or "ha_vm".
	// Enum: [vsi ha_vm]
	DNSType *string `json:"dns_type,omitempty"`

	// Domain type. "primary" is the only supported value currently.
	// Enum: [primary]
	DomainType *string `json:"domain_type,omitempty"`

	// edge
	// Required: true
	Edge *EdgeMultiCluster `json:"edge"`

	// Hostname prefix of the VMware vSphere hosts.
	HostPrefix *string `json:"host_prefix,omitempty"`

	// license keys
	// Required: true
	LicenseKeys *VcsEdgeOrderDataLicenseKeys `json:"license_keys"`

	// management
	// Required: true
	Management *MultiCluster `json:"management"`

	// New VMware instance name that must be unique in your account.
	// Required: true
	// Max Length: 10
	Name *string `json:"name"`

	// Root domain of the VMware vSphere hosts.
	// Required: true
	RootDomain *string `json:"root_domain"`

	// List of services to be added to the instance.
	Services []*ServiceInfo `json:"services"`

	// Subdomain of the VMware vSphere hosts.
	Subdomain *string `json:"subdomain,omitempty"`

	// vcs type
	VcsType VcsType `json:"vcs_type,omitempty"`

	// vSphere version. To list supported vSphere versions, use the `GET /v2/vsphere_versions` API. Use "latest" to specify the latest supported vSphere version.
	VsphereVersion *string `json:"vsphere_version,omitempty"`
}

// Validate validates this vcs edge order data
func (m *VcsEdgeOrderData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDNSType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEdge(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLicenseKeys(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateManagement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRootDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServices(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVcsType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var vcsEdgeOrderDataTypeDNSTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["vsi","ha_vm"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		vcsEdgeOrderDataTypeDNSTypePropEnum = append(vcsEdgeOrderDataTypeDNSTypePropEnum, v)
	}
}

const (

	// VcsEdgeOrderDataDNSTypeVsi captures enum value "vsi"
	VcsEdgeOrderDataDNSTypeVsi string = "vsi"

	// VcsEdgeOrderDataDNSTypeHaVM captures enum value "ha_vm"
	VcsEdgeOrderDataDNSTypeHaVM string = "ha_vm"
)

// prop value enum
func (m *VcsEdgeOrderData) validateDNSTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, vcsEdgeOrderDataTypeDNSTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *VcsEdgeOrderData) validateDNSType(formats strfmt.Registry) error {

	if swag.IsZero(m.DNSType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDNSTypeEnum("dns_type", "body", *m.DNSType); err != nil {
		return err
	}

	return nil
}

var vcsEdgeOrderDataTypeDomainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["primary"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		vcsEdgeOrderDataTypeDomainTypePropEnum = append(vcsEdgeOrderDataTypeDomainTypePropEnum, v)
	}
}

const (

	// VcsEdgeOrderDataDomainTypePrimary captures enum value "primary"
	VcsEdgeOrderDataDomainTypePrimary string = "primary"
)

// prop value enum
func (m *VcsEdgeOrderData) validateDomainTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, vcsEdgeOrderDataTypeDomainTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *VcsEdgeOrderData) validateDomainType(formats strfmt.Registry) error {

	if swag.IsZero(m.DomainType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDomainTypeEnum("domain_type", "body", *m.DomainType); err != nil {
		return err
	}

	return nil
}

func (m *VcsEdgeOrderData) validateEdge(formats strfmt.Registry) error {

	if err := validate.Required("edge", "body", m.Edge); err != nil {
		return err
	}

	if m.Edge != nil {
		if err := m.Edge.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("edge")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderData) validateLicenseKeys(formats strfmt.Registry) error {

	if err := validate.Required("license_keys", "body", m.LicenseKeys); err != nil {
		return err
	}

	if m.LicenseKeys != nil {
		if err := m.LicenseKeys.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_keys")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderData) validateManagement(formats strfmt.Registry) error {

	if err := validate.Required("management", "body", m.Management); err != nil {
		return err
	}

	if m.Management != nil {
		if err := m.Management.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("management")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderData) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(*m.Name), 10); err != nil {
		return err
	}

	return nil
}

func (m *VcsEdgeOrderData) validateRootDomain(formats strfmt.Registry) error {

	if err := validate.Required("root_domain", "body", m.RootDomain); err != nil {
		return err
	}

	return nil
}

func (m *VcsEdgeOrderData) validateServices(formats strfmt.Registry) error {

	if swag.IsZero(m.Services) { // not required
		return nil
	}

	for i := 0; i < len(m.Services); i++ {
		if swag.IsZero(m.Services[i]) { // not required
			continue
		}

		if m.Services[i] != nil {
			if err := m.Services[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("services" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *VcsEdgeOrderData) validateVcsType(formats strfmt.Registry) error {

	if swag.IsZero(m.VcsType) { // not required
		return nil
	}

	if err := m.VcsType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("vcs_type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VcsEdgeOrderData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VcsEdgeOrderData) UnmarshalBinary(b []byte) error {
	var res VcsEdgeOrderData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VcsEdgeOrderDataLicenseKeys VMware license keys configuration.
// swagger:model VcsEdgeOrderDataLicenseKeys
type VcsEdgeOrderDataLicenseKeys struct {

	// nsx
	Nsx *NsxLicense `json:"nsx,omitempty"`

	// vcenter
	Vcenter *VcenterLicense `json:"vcenter,omitempty"`

	// vsan
	Vsan *VsanLicense `json:"vsan,omitempty"`

	// vsphere
	Vsphere *VsphereLicense `json:"vsphere,omitempty"`
}

// Validate validates this vcs edge order data license keys
func (m *VcsEdgeOrderDataLicenseKeys) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNsx(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVcenter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVsan(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVsphere(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VcsEdgeOrderDataLicenseKeys) validateNsx(formats strfmt.Registry) error {

	if swag.IsZero(m.Nsx) { // not required
		return nil
	}

	if m.Nsx != nil {
		if err := m.Nsx.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_keys" + "." + "nsx")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderDataLicenseKeys) validateVcenter(formats strfmt.Registry) error {

	if swag.IsZero(m.Vcenter) { // not required
		return nil
	}

	if m.Vcenter != nil {
		if err := m.Vcenter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_keys" + "." + "vcenter")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderDataLicenseKeys) validateVsan(formats strfmt.Registry) error {

	if swag.IsZero(m.Vsan) { // not required
		return nil
	}

	if m.Vsan != nil {
		if err := m.Vsan.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_keys" + "." + "vsan")
			}
			return err
		}
	}

	return nil
}

func (m *VcsEdgeOrderDataLicenseKeys) validateVsphere(formats strfmt.Registry) error {

	if swag.IsZero(m.Vsphere) { // not required
		return nil
	}

	if m.Vsphere != nil {
		if err := m.Vsphere.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_keys" + "." + "vsphere")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VcsEdgeOrderDataLicenseKeys) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VcsEdgeOrderDataLicenseKeys) UnmarshalBinary(b []byte) error {
	var res VcsEdgeOrderDataLicenseKeys
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
