// Code generated by go-swagger; DO NOT EDIT.

package vcenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IBM-Cloud/vcds-go-client/vcds/models"
)

// NewControllersPublicV1ProxyOrderMcvParams creates a new ControllersPublicV1ProxyOrderMcvParams object
// with the default values initialized.
func NewControllersPublicV1ProxyOrderMcvParams() *ControllersPublicV1ProxyOrderMcvParams {
	var (
		checkPriceDefault = bool(false)
		verifyOnlyDefault = bool(false)
	)
	return &ControllersPublicV1ProxyOrderMcvParams{
		CheckPrice: &checkPriceDefault,
		VerifyOnly: &verifyOnlyDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV1ProxyOrderMcvParamsWithTimeout creates a new ControllersPublicV1ProxyOrderMcvParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV1ProxyOrderMcvParamsWithTimeout(timeout time.Duration) *ControllersPublicV1ProxyOrderMcvParams {
	var (
		checkPriceDefault = bool(false)
		verifyOnlyDefault = bool(false)
	)
	return &ControllersPublicV1ProxyOrderMcvParams{
		CheckPrice: &checkPriceDefault,
		VerifyOnly: &verifyOnlyDefault,

		timeout: timeout,
	}
}

// NewControllersPublicV1ProxyOrderMcvParamsWithContext creates a new ControllersPublicV1ProxyOrderMcvParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV1ProxyOrderMcvParamsWithContext(ctx context.Context) *ControllersPublicV1ProxyOrderMcvParams {
	var (
		checkPriceDefault = bool(false)
		verifyOnlyDefault = bool(false)
	)
	return &ControllersPublicV1ProxyOrderMcvParams{
		CheckPrice: &checkPriceDefault,
		VerifyOnly: &verifyOnlyDefault,

		Context: ctx,
	}
}

// NewControllersPublicV1ProxyOrderMcvParamsWithHTTPClient creates a new ControllersPublicV1ProxyOrderMcvParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV1ProxyOrderMcvParamsWithHTTPClient(client *http.Client) *ControllersPublicV1ProxyOrderMcvParams {
	var (
		checkPriceDefault = bool(false)
		verifyOnlyDefault = bool(false)
	)
	return &ControllersPublicV1ProxyOrderMcvParams{
		CheckPrice: &checkPriceDefault,
		VerifyOnly: &verifyOnlyDefault,
		HTTPClient: client,
	}
}

/*ControllersPublicV1ProxyOrderMcvParams contains all the parameters to send to the API endpoint
for the controllers public v1 proxy order mcv operation typically these are written to a http.Request
*/
type ControllersPublicV1ProxyOrderMcvParams struct {

	/*Authorization
	  Your IBM Cloud Identity and Access Management (IAM) token. To retrieve your IAM token, run `ibmcloud iam oauth-tokens`.

	*/
	Authorization string
	/*CheckPrice
	  Whether to display the high-level price associated with the order.

	*/
	CheckPrice *bool
	/*McvOrderData
	  Order specification with configurations.

	*/
	McvOrderData *models.McvOrderData
	/*VerifyOnly
	  Whether to verify the order only instead of performing the order for real.

	*/
	VerifyOnly *bool
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithTimeout(timeout time.Duration) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithContext(ctx context.Context) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithHTTPClient(client *http.Client) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithAuthorization(authorization string) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithCheckPrice adds the checkPrice to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithCheckPrice(checkPrice *bool) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetCheckPrice(checkPrice)
	return o
}

// SetCheckPrice adds the checkPrice to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetCheckPrice(checkPrice *bool) {
	o.CheckPrice = checkPrice
}

// WithMcvOrderData adds the mcvOrderData to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithMcvOrderData(mcvOrderData *models.McvOrderData) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetMcvOrderData(mcvOrderData)
	return o
}

// SetMcvOrderData adds the mcvOrderData to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetMcvOrderData(mcvOrderData *models.McvOrderData) {
	o.McvOrderData = mcvOrderData
}

// WithVerifyOnly adds the verifyOnly to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithVerifyOnly(verifyOnly *bool) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetVerifyOnly(verifyOnly)
	return o
}

// SetVerifyOnly adds the verifyOnly to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetVerifyOnly(verifyOnly *bool) {
	o.VerifyOnly = verifyOnly
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV1ProxyOrderMcvParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v1 proxy order mcv params
func (o *ControllersPublicV1ProxyOrderMcvParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV1ProxyOrderMcvParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.CheckPrice != nil {

		// query param check_price
		var qrCheckPrice bool
		if o.CheckPrice != nil {
			qrCheckPrice = *o.CheckPrice
		}
		qCheckPrice := swag.FormatBool(qrCheckPrice)
		if qCheckPrice != "" {
			if err := r.SetQueryParam("check_price", qCheckPrice); err != nil {
				return err
			}
		}

	}

	if o.McvOrderData != nil {
		if err := r.SetBodyParam(o.McvOrderData); err != nil {
			return err
		}
	}

	if o.VerifyOnly != nil {

		// query param verify_only
		var qrVerifyOnly bool
		if o.VerifyOnly != nil {
			qrVerifyOnly = *o.VerifyOnly
		}
		qVerifyOnly := swag.FormatBool(qrVerifyOnly)
		if qVerifyOnly != "" {
			if err := r.SetQueryParam("verify_only", qVerifyOnly); err != nil {
				return err
			}
		}

	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
