// Code generated by go-swagger; DO NOT EDIT.

package vcenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV1ProxyDeleteVcenterClusterParams creates a new ControllersPublicV1ProxyDeleteVcenterClusterParams object
// with the default values initialized.
func NewControllersPublicV1ProxyDeleteVcenterClusterParams() *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	var ()
	return &ControllersPublicV1ProxyDeleteVcenterClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithTimeout creates a new ControllersPublicV1ProxyDeleteVcenterClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithTimeout(timeout time.Duration) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	var ()
	return &ControllersPublicV1ProxyDeleteVcenterClusterParams{

		timeout: timeout,
	}
}

// NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithContext creates a new ControllersPublicV1ProxyDeleteVcenterClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithContext(ctx context.Context) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	var ()
	return &ControllersPublicV1ProxyDeleteVcenterClusterParams{

		Context: ctx,
	}
}

// NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithHTTPClient creates a new ControllersPublicV1ProxyDeleteVcenterClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV1ProxyDeleteVcenterClusterParamsWithHTTPClient(client *http.Client) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	var ()
	return &ControllersPublicV1ProxyDeleteVcenterClusterParams{
		HTTPClient: client,
	}
}

/*ControllersPublicV1ProxyDeleteVcenterClusterParams contains all the parameters to send to the API endpoint
for the controllers public v1 proxy delete vcenter cluster operation typically these are written to a http.Request
*/
type ControllersPublicV1ProxyDeleteVcenterClusterParams struct {

	/*Authorization
	  Your IBM Cloud Identity and Access Management (IAM) token. To retrieve your IAM token, run `ibmcloud iam oauth-tokens`.

	*/
	Authorization string
	/*ClusterID
	  Cluster ID.

	*/
	ClusterID string
	/*InstanceID
	  Instance ID.

	*/
	InstanceID string
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithTimeout(timeout time.Duration) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithContext(ctx context.Context) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithHTTPClient(client *http.Client) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithAuthorization(authorization string) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithClusterID adds the clusterID to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithClusterID(clusterID string) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithInstanceID adds the instanceID to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithInstanceID(instanceID string) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV1ProxyDeleteVcenterClusterParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v1 proxy delete vcenter cluster params
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV1ProxyDeleteVcenterClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
