// Code generated by go-swagger; DO NOT EDIT.

package vcenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV2ProxyListVcenterClustersParams creates a new ControllersPublicV2ProxyListVcenterClustersParams object
// with the default values initialized.
func NewControllersPublicV2ProxyListVcenterClustersParams() *ControllersPublicV2ProxyListVcenterClustersParams {
	var ()
	return &ControllersPublicV2ProxyListVcenterClustersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV2ProxyListVcenterClustersParamsWithTimeout creates a new ControllersPublicV2ProxyListVcenterClustersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV2ProxyListVcenterClustersParamsWithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListVcenterClustersParams {
	var ()
	return &ControllersPublicV2ProxyListVcenterClustersParams{

		timeout: timeout,
	}
}

// NewControllersPublicV2ProxyListVcenterClustersParamsWithContext creates a new ControllersPublicV2ProxyListVcenterClustersParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV2ProxyListVcenterClustersParamsWithContext(ctx context.Context) *ControllersPublicV2ProxyListVcenterClustersParams {
	var ()
	return &ControllersPublicV2ProxyListVcenterClustersParams{

		Context: ctx,
	}
}

// NewControllersPublicV2ProxyListVcenterClustersParamsWithHTTPClient creates a new ControllersPublicV2ProxyListVcenterClustersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV2ProxyListVcenterClustersParamsWithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListVcenterClustersParams {
	var ()
	return &ControllersPublicV2ProxyListVcenterClustersParams{
		HTTPClient: client,
	}
}

/*ControllersPublicV2ProxyListVcenterClustersParams contains all the parameters to send to the API endpoint
for the controllers public v2 proxy list vcenter clusters operation typically these are written to a http.Request
*/
type ControllersPublicV2ProxyListVcenterClustersParams struct {

	/*Authorization
	  Your IBM Cloud Identity and Access Management (IAM) token. To retrieve your IAM token, run `ibmcloud iam oauth-tokens`.

	*/
	Authorization string
	/*InstanceID
	  Instance ID.

	*/
	InstanceID string
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithTimeout(timeout time.Duration) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithContext(ctx context.Context) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithHTTPClient(client *http.Client) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithAuthorization(authorization string) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithInstanceID adds the instanceID to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithInstanceID(instanceID string) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV2ProxyListVcenterClustersParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v2 proxy list vcenter clusters params
func (o *ControllersPublicV2ProxyListVcenterClustersParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV2ProxyListVcenterClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
