// Code generated by go-swagger; DO NOT EDIT.

package vcenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams creates a new ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams object
// with the default values initialized.
func NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams() *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	var ()
	return &ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithTimeout creates a new ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithTimeout(timeout time.Duration) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	var ()
	return &ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams{

		timeout: timeout,
	}
}

// NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithContext creates a new ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithContext(ctx context.Context) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	var ()
	return &ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams{

		Context: ctx,
	}
}

// NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithHTTPClient creates a new ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParamsWithHTTPClient(client *http.Client) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	var ()
	return &ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams{
		HTTPClient: client,
	}
}

/*ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams contains all the parameters to send to the API endpoint
for the controllers public v1 proxy batch delete vcenter nfs storage operation typically these are written to a http.Request
*/
type ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams struct {

	/*Authorization
	  Your IBM Cloud Identity and Access Management (IAM) token. To retrieve your IAM token, run `ibmcloud iam oauth-tokens`.

	*/
	Authorization string
	/*ClusterID
	  Cluster ID.

	*/
	ClusterID string
	/*InstanceID
	  Instance ID.

	*/
	InstanceID string
	/*NfsDeleteData
	  NFS storage ID list for deleting.

	*/
	NfsDeleteData ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageBody
	/*XGlobalTransactionID
	  Global transaction ID for request correlation.

	*/
	XGlobalTransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithTimeout(timeout time.Duration) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithContext(ctx context.Context) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithHTTPClient(client *http.Client) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithAuthorization(authorization string) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithClusterID adds the clusterID to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithClusterID(clusterID string) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithInstanceID adds the instanceID to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithInstanceID(instanceID string) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithNfsDeleteData adds the nfsDeleteData to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithNfsDeleteData(nfsDeleteData ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageBody) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetNfsDeleteData(nfsDeleteData)
	return o
}

// SetNfsDeleteData adds the nfsDeleteData to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetNfsDeleteData(nfsDeleteData ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageBody) {
	o.NfsDeleteData = nfsDeleteData
}

// WithXGlobalTransactionID adds the xGlobalTransactionID to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WithXGlobalTransactionID(xGlobalTransactionID *string) *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams {
	o.SetXGlobalTransactionID(xGlobalTransactionID)
	return o
}

// SetXGlobalTransactionID adds the xGlobalTransactionId to the controllers public v1 proxy batch delete vcenter nfs storage params
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) SetXGlobalTransactionID(xGlobalTransactionID *string) {
	o.XGlobalTransactionID = xGlobalTransactionID
}

// WriteToRequest writes these params to a swagger request
func (o *ControllersPublicV1ProxyBatchDeleteVcenterNfsStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.NfsDeleteData); err != nil {
		return err
	}

	if o.XGlobalTransactionID != nil {

		// header param x-global-transaction-id
		if err := r.SetHeaderParam("x-global-transaction-id", *o.XGlobalTransactionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
