// Code generated by go-swagger; DO NOT EDIT.

package users_and_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new users and accounts API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for users and accounts API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ControllersPublicV1ProxySetSlAccountKeyBssaccount sets the i b m cloud infrastructure account user ID and API key for linked i b m cloud account

If no request body is provided, retrieve the user name and API key for the IBM Cloud infrastructure account that is linked to the current IBM Cloud account. Then enter the information in the VMware Solutions account settings. If a request body is provided, set the provided user name and API key for the IBM Cloud infrastructure account in the VMware Solutions account settings.
*/
func (a *Client) ControllersPublicV1ProxySetSlAccountKeyBssaccount(params *ControllersPublicV1ProxySetSlAccountKeyBssaccountParams) (*ControllersPublicV1ProxySetSlAccountKeyBssaccountOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewControllersPublicV1ProxySetSlAccountKeyBssaccountParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "controllers.public.v1.proxy.set_sl_account_key_bssaccount",
		Method:             "POST",
		PathPattern:        "/v1/infra_credentials",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ControllersPublicV1ProxySetSlAccountKeyBssaccountReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ControllersPublicV1ProxySetSlAccountKeyBssaccountOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
